### ISSUE TITLE
When leaflet with sidebar-v2 incorporated in bootstrap pages .sidebar common class name collides

### ISSUE THREAD

**Issue by devleaks** [nickpeihl/leaflet-sidebar-v2#13]
Common .sidebar css class name collides with bootstrap .sidebar.
Is it conceivable to either change this package's .sidebar css classname to .leaflet-sidebar-v2 (for instance) or make this class name a parameter?
Thank you.

**Comment by noerw** [comment]
Indeed, the class names are not great indeed.
I would prefix the class names with `leaflet-`, but this would be a breaking change for `v3.0.0`.
Using the old classes as fallback is no option in CSS unfortunately..

**Comment by nickpeihl** [comment]
I support this idea for `v3.0.0`.

**Comment by devleaks** [comment]
OK thanks. Well you got the idea. We must find a way to make the .sidebar selector more precise.
You could contextualize it into a #{sidebar-element-id}, or something else.
I think that a simpler rename with a less generic name is the easiest solution.
Thanks. P.

**Comment by noerw** [comment]
fixed in [`v3.0.0`](https://github.com/nickpeihl/leaflet-sidebar-v2/commit/5833694b441b07b27bdf77613bee17c652a12cd9)
