### ISSUE TITLE
[Request] Add panel-less button using html

### ISSUE THREAD

**Issue by ChaudhryAtif** [nickpeihl/leaflet-sidebar-v2#17]
A tab-less button listener can be added via the following js:
```
/* add an button with click listener */
sidebar.addPanel({
    id: 'click',
    tab: '<i class="fa fa-info"></i>',
    button: function (event) { console.log(event); }
});
```

It can be done through html (with some help of js) like so:
```
<ul role="tablist">
    <li><a href="javascript:void(0);" onclick="myFunction()"><i class="fa fa-gear"></i></a></li>
</ul>
```
---

Can the following additions be made so that any anchor with a specific class can be made into a panel-less button? I would do a PR, but I haven't done too much of scss to css build and all, so suggesting it instead.
```
// css
.leaflet-sidebar-button {
    cursor: pointer;
}

// html
<ul role="tablist">
    <li><a class="leaflet-sidebar-button" onclick="myFunction()"><i class="fa fa-gear"></i></a></li>
</ul>

// js
if ((link.hasAttribute('href') && link.getAttribute('href')[0] !== '#' ) || (link.classList.contains("leaflet-sidebar-button"))
    return;
```

[classList browser support + more info](https://stackoverflow.com/a/16337545/5003918)

https://github.com/nickpeihl/leaflet-sidebar-v2/blob/09086d779e4fd04e3a65aa8031e340e8a3691bbe/js/leaflet-sidebar.js#L426
Note: Although the code checks if the first character is '#' (and returns if it doesn't), it doesn't work as expected all the time (i.e. for Angular).

**Comment by noerw** [comment]
I will look into it.
For the CSS we don't need a new class, [this selector](https://github.com/nickpeihl/leaflet-sidebar-v2/blob/71f4d10/scss/_base.scss#L122-L125) should work well.

Do you have a suggestion for a better check than `href[0] !== '#'`?

**Comment by ChaudhryAtif** [comment]
I'm not sure about a better check for href[0], but updating 
`if (link.hasAttribute('href') && link.getAttribute('href')[0] !== '#')`
to
`if (!link.hasAttribute('href') || link.getAttribute('href')[0] !== '#'))`
would probably be good regardless.

How would this feature impact sidebar.addPanel? One pro of using a class is that sidebar.addPanel would need less changes. You could add an optional property (i.e. anchorClass or tabClass) to set anchor's class when adding it via js, and both should work as expected.

**Comment by nickpeihl** [comment]
The proposed change would allow a sidebar button to act externally of the the sidebar. For example, clicking a gear button on the sidebar could open a modal window rather than a sidebar tab. Please let me know if I'm mistaken.

I'm cautiously supportive of the idea. Implementation needs careful consideration though. 

I'm unable to see how the proposed link check would be better. Can someone provide an example? [Here's a quick jsbin](http://jsbin.com/tuzexusafu/edit?html,js,console,output) that compares the existing and proposed link checks with a few scenarios.

**Comment by noerw** [comment]
@nickpeihl [This feature exists already](https://github.com/nickpeihl/leaflet-sidebar-v2/blob/master/js/leaflet-sidebar.js#L282). What @ChaudhryAtif wants, is to support this in the html-markup version as well.

The change of the check allows to omit the `href="javascript:void(0);"` attribute for button-tabs in the markup. ([Here's the same test, reworded](http://jsbin.com/homezagijo/1/edit?html,js,console,output))

**Comment by nickpeihl** [comment]
@noerw That makes sense to me. Thanks so much for explaining! I'm definitely in favor of this improvement.

**Comment by noerw** [comment]
fixed in 78e4787f06baf4559ed48ef5fff3ec5018fd7bfe

**Comment by ChaudhryAtif** [comment]
Does this account for href being added by addPanel?

**Comment by noerw** [comment]
Why wouldn't it? I tested this, and everything kept working

**Comment by ChaudhryAtif** [comment]
Alright. Thanks for adding the feature!

**Comment by ChaudhryAtif** [comment]
@noerw 3.0.1 is the latest npm: https://www.npmjs.com/package/leaflet-sidebar-v2

**Comment by noerw** [comment]
sorry. just pushed 3.0.2
