### ISSUE TITLE
Add and removing panel more than twice

### ISSUE THREAD

**Issue by lmgarret** [nickpeihl/leaflet-sidebar-v2#24]
Hi! I have noticed an issue which happens when calling `removePanel`and `addPanel` methods more than twice with the same panel. This leads to the panel not being removed. 

I believe the solution here is to change this [line](https://github.com/nickpeihl/leaflet-sidebar-v2/blob/6e56b0ef2244b6952831f0c055a4eadc34693369/js/leaflet-sidebar.js#L367) from `this._tabitems.slice(i, 1);` to `this._tabitems.splice(i, 1);` and do the same for panes.

Best regards!

**EDIT** updated suggested fix

**Comment by noerw** [comment]
Hey @lmgarret, good catch and thanks for looking for a solution!
Will be fixed in version 3.0.3, to be released later today.
