### ISSUE TITLE
Create Sidebar Footer

### ISSUE THREAD

**Issue by arthurgailes** [nickpeihl/leaflet-sidebar-v2#36]
Hello,

I'd like to create a sidebar footer in the same manner as the header - where it stays in the same relative space in the screen and the main body ignores it for scrolling purposes. Could you let me know what the css properties the header uses that allows that? I couldn't figure it out from the file.

Thank you!

**Comment by noerw** [comment]
Hi,
I'm not sure what you mean, the panel header scrolls with the content and is not fixed afaik.

![image](https://user-images.githubusercontent.com/7880552/59460431-6029e700-8e1f-11e9-9ce1-ebfef0d03778.png)
![image](https://user-images.githubusercontent.com/7880552/59460452-6ae47c00-8e1f-11e9-842d-214ea5cb535d.png)

In general, you can achieve a fixed element via the `position: fixed` CSS attribute.

**Comment by arthurgailes** [comment]
I apologize; my mistake.
