### ISSUE TITLE
.remove() doesn't work on Leaflet v1.5.0+

### ISSUE THREAD

**Issue by sio2sio2** [nickpeihl/leaflet-sidebar-v2#37]
On Leaflet v1.5.0+ removing the sidebar from the map does not work:

~~~
Uncaught TypeError: Cannot read property 'off' of null (Control.js:100)
~~~

After invoking ``sidebar.onRemove()``, Leaflet v1.5.0+ try to use ``sidebar._map``, but ``.onRemove()`` has already set [sidebar._map to null](https://github.com/nickpeihl/leaflet-sidebar-v2/blob/master/js/leaflet-sidebar.js#L150).

Sorry for my bad English.

**Comment by noerw** [comment]
Thanks for reporting, will fix asap!
