### ISSUE TITLE
Is it possible that the button is on the right side?

### ISSUE THREAD

**Issue by iByteDev** [nickpeihl/leaflet-sidebar-v2#42]
Currently, when clicking on a tab icon, open the panel correctly. What I want to do is that the buttons run to the right side of the tab that is displayed. Is this possible?
![troubble](https://user-images.githubusercontent.com/49767173/68499243-b9f3d900-0226-11ea-81d0-8fbbea3a63b0.png)

**Comment by noerw** [comment]
The style does not support this, unless the sidebar is right aligned.
You could adapt the SCSS yourself though.
