### ISSUE TITLE
Can't refresh content

### ISSUE THREAD

**Issue by huemaj** [nickpeihl/leaflet-sidebar-v2#51]
Hello,

I have a problem when using leaflet and the sidebar in combination with AngularJS.

I have some options on the marker and I put the selected marker in a variable called clickedMarker.

$scope.clickedMarker = e.target;

I then open the sidebar tab and try to display the name of the  marker, but it doesn't do it.

<h4>Object - {{clickedMarker.options.ObjectName}}</h4>

If I open or close the developer tool in chrome(F12) the name get's refreshed.

Is it a bug? Any suggestions or workarounds?

**Comment by noerw** [comment]
I'm not firm with Angular specific problems, I can't provide support for that here.

Just a hint: content only updating on viewport resize is related to modifications of the DOM outside of angular. You need to manually apply the $scope or something..
