### ISSUE TITLE
Couple of bug reports/fixes....

### ISSUE THREAD

**Issue by bqtran** [nickpeihl/leaflet-sidebar-v2#6]
Loving what you did to improve upon the original! Definitely help kept my code more modular/cleaner, though I did run into a couple of bugs that you may want to fix:

1) Using addPanel in addition to addTo functions will effectively double up on the click events for tabs and close icons. This will cause the bar to open & close quickly and make it seem like nothing's working to the user.

2) Ln 255 should be using setAttribute('role','tab') instead, otherwise the attribute won't appear like the original plugin.

3) Similar to #2, the tab containers (both top and bottom) are missing a setAttribute('role', 'tablist') attribute to match the original sidebar-v2.

Thanks for the work!

**Comment by nickpeihl** [comment]
Hi @bqtran! Thanks for reporting this. Would you be willing to do a pull request to fix this? It may be a while before I come back around and work on this.
